AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Greeting API written in jersey with the aws-serverless-java-container library
Resources:
  PetStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.aws.samples.compute.greeting.serverless.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/greeting-lambda-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  GreetingServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/resources/greeting'
    Export:
Name: GreetingServiceApi