AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Greeting API written in jersey with the aws-serverless-java-container library
Resources:

  ResourcesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "Sample API"
        paths:
          "/":
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebAppFunction.Arn}/invocations
                responses: {}
          "/resources/greeting":
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GreetingFunction.Arn}/invocations
              responses: {}
          "/resources/names":
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${NameFunction.Arn}/invocations
              responses: {}
          "/resources/names/{id}":
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${NameFunction.Arn}/invocations
              responses: {}

  WebAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.aws.samples.compute.webapp.serverless.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: ../../services/jar/webapp/target/webapp-jar-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Environment:
        Variables:
          GREETING_SERVICE_HOST: !Sub "${ResourcesApi}.execute-api.${AWS::Region}.amazonaws.com"
          GREETING_SERVICE_PORT: "443"
          GREETING_SERVICE_PATH: "/Prod/resources/greeting"
          NAME_SERVICE_HOST: !Sub "${ResourcesApi}.execute-api.${AWS::Region}.amazonaws.com"
          NAME_SERVICE_PORT: "443"
          NAME_SERVICE_PATH: "/Prod/resources/names"
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId:
              Ref: ResourcesApi
            Path: /
            Method: get

  GreetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.aws.samples.compute.greeting.serverless.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: ../../services/jar/greeting/target/greeting-jar-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId:
              Ref: ResourcesApi
            Path: /resources/greeting
            Method: get

  NameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.aws.samples.compute.name.serverless.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: ../../services/jar/name/target/name-jar-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId:
              Ref: ResourcesApi
            Path: /resources/names
            Method: get
        GetByIdResource:
          Type: Api
          Properties:
            RestApiId:
              Ref: ResourcesApi
            Path: /resources/names/{id}
            Method: get


Outputs:
  SampleServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ResourcesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/resources/greeting'
    Export:
      Name: SampleServiceApi
